/**
 * Redux constants for TabNavigator backend requests
 */

export const START_POLLING_NUMBER_OF_UNREAD_MESSAGES =
  'START_POLLING_NUMBER_OF_UNREAD_MESSAGES'
export const POLLING_NUMBER_OF_UNREAD_MESSAGES_ERROR =
  'POLLING_NUMBER_OF_UNREAD_MESSAGES_ERROR'
export const POLLING_NUMBER_OF_UNREAD_MESSAGES_SUCCESS =
  'POLLING_NUMBER_OF_UNREAD_MESSAGES_SUCCESS'
export const CANCEL_POLLING_NUMBER_OF_UNREAD_MESSAGES =
  'CANCEL_POLLING_NUMBER_OF_UNREAD_MESSAGES'
