/**
 * Redux constants for AccountManagementScreen backend requests
 */

export const FETCH_USER_DATA = 'FETCH_USER_DATA'
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS'
export const FETCH_USER_DATA_ERROR = 'FETCH_USER_DATA_ERROR'

export const UPDATE_USER_AND_ROLE = 'UPDATE_USER_AND_ROLE'
export const UPDATE_USER_AND_ROLE_SUCCESS = 'UPDATE_USER_AND_ROLE_SUCCESS'
export const UPDATE_USER_AND_ROLE_ERROR = 'UPDATE_USER_AND_ROLE_ERROR'
export const RESET_UPDATE_USER_AND_ROLE_ERROR =
  'RESET_UPDATE_USER_AND_ROLE_ERROR'
