/**
 * Redux constants for StatisticsScreen backend requests
 */
export const GET_PIE_CHART_STATS = 'GET_PIE_CHART_STATS'
export const GET_PIE_CHART_STATS_SUCCESS = 'GET_PIE_CHART_STATS_SUCCESS'
export const GET_PIE_CHART_STATS_ERROR = 'GET_PIE_CHART_STATS_ERROR'

export const GET_BAR_CHART_STATS = 'GET_BAR_CHART_STATS'
export const GET_BAR_CHART_STATS_SUCCESS = 'GET_BAR_CHART_STATS_SUCCESS'
export const GET_BAR_CHART_STATS_ERROR = 'GET_BAR_CHART_STATS_ERROR'
