/**
 * Redux constants for UserRegistration backend requests
 */

export const FETCH_INSTITUTES = 'FETCH_INSTITUTES'
export const FETCH_INSTITUTES_SUCCESS = 'FETCH_INSTITUTES_SUCCESS'
export const FETCH_INSTITUTES_ERROR = 'FETCH_INSTITUTES_ERROR'

export const FETCH_FIELDS = 'FETCH_FIELDS'
export const FETCH_FIELDS_SUCCESS = 'FETCH_FIELDS_SUCCESS'
export const FETCH_FIELDS_ERROR = 'FETCH_FIELDS_ERROR'

export const FETCH_COURSES = 'FETCH_COURSES'
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS'
export const FETCH_COURSES_ERROR = 'FETCH_COURSES_ERROR'

export const CREATE_USER_AND_ROLE = 'CREATE_USER_AND_ROLE'
export const CREATE_USER_AND_ROLE_SUCCESS = 'CREATE_USER_AND_ROLE_SUCCESS'
export const CREATE_USER_AND_ROLE_ERROR = 'CREATE_USER_AND_ROLE_ERROR'
export const RESET_CREATE_USER_AND_ROLE_ERROR =
  'RESET_CREATE_USER_AND_ROLE_ERROR'
