/**
 * Redux constants for AddresseeListScreen backend requests
 */

export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS'
export const GET_RECOMMENDATIONS_SUCCESS = 'GET_RECOMMENDATIONS_SUCCESS'
export const GET_RECOMMENDATIONS_ERROR = 'GET_RECOMMENDATIONS_ERROR'

export const FILTER_USER = 'FILTER_USER'
export const FILTER_USER_SUCCESS = 'FILTER_USER_SUCCESS'
export const FILTER_USER_ERROR = 'FILTER_USER_ERROR'
